version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily" }
  - package-ecosystem: "composer"
    directory: "laravel"
    schedule: { interval: "daily" }
  - package-ecosystem: "npm"
    directory: "laravel"
    schedule: { interval: "daily" }
