AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Aurora Serverless DB Cluster
Resources:
  Secrets:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Join ["-", [!Ref "AWS::StackName", "secrets"]]
      GenerateSecretString:
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
  Aurora:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref Secrets, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref Secrets, ':SecretString:password}}' ]]
      DBClusterIdentifier: !Ref "AWS::StackName"
      Engine: aurora-mysql
      EngineVersion: 5.7.12
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 1
        MaxCapacity: 1
        SecondsUntilAutoPause: 300
  LinkSecretsToAurora:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref Secrets
      TargetId: !Ref Aurora
      TargetType: AWS::RDS::DBCluster
