AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM & Laravel template using bref.
Parameters:
  CertificateARN:
    Type: String
  DomainName:
    Type: String
  WildcardCertificateARN:
    Type: String
  Route53HostedZoneId:
    Type: String
    Description: 'The hosted zone ID which the base domain resides.'
Resources:
  Laravel:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Tracing: Active
      MemorySize: 1024
      CodeUri: .
      Layers: ["arn:aws:lambda:eu-west-1:209497400698:layer:php-80-fpm:9"]
      Handler: public/index.php
      Runtime: provided.al2
      Environment:
        Variables:
          APP_STORAGE: /tmp
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
  Domain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt
          - CDN
          - DomainName
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardCertificateARN
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        Enabled: true
        Aliases: [!Ref DomainName]
        Origins:
          - Id: LaravelOriginId
            DomainName: !Join [ '.', [ !Ref ServerlessHttpApi, 'execute-api', !Ref AWS::Region, 'amazonaws.com' ] ]
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only' # API Gateway only supports HTTPS
#          # The assets (S3)
#          - Id: Assets
#            DomainName: !GetAtt Assets.RegionalDomainName
#            S3OriginConfig: { } # this key is required to tell CloudFront that this is an S3 origin, even though nothing is configured
        DefaultCacheBehavior:
          AllowedMethods: [ GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE ]
          TargetOriginId: LaravelOriginId
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            # We must *not* forward the `Host` header else it messes up API Gateway
            Headers:
              - 'Accept'
              - 'Accept-Language'
              - 'Origin'
              - 'Referer'
          ViewerProtocolPolicy: redirect-to-https
#        CacheBehaviors:
#          # Assets will be served under the `/assets/` prefix
#          - PathPattern: 'assets/*'
#            TargetOriginId: Assets # the static files on S3
#            AllowedMethods: [ GET, HEAD ]
#            ViewerProtocolPolicy: redirect-to-https
#            ForwardedValues:
#              # No need for all that with assets
#              QueryString: 'false'
#              Cookies:
#                Forward: none
#            #ViewerProtocolPolicy: redirect-to-https
#            Compress: true
Outputs:
  Domain:
    Value: !Sub "https://${DomainName}"
