AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  The certificate for the subdomain.

  CloudFront only supports ACM certificates in the US East (N. Virginia) Region (us-east-1).
  Thus this template is created separately on the us-east-1 region.

Parameters:
  DomainName:
    Type: String
  BaseDomainRoute53HostedZoneId:
    Type: String
    Description: 'The hosted zone ID which the base domain resides.'
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref BaseDomainRoute53HostedZoneId
      DomainName: !Ref DomainName
Outputs:
  CertificateARN:
    Value: !Ref Certificate
